apiVersion: carto.run/v1alpha1
kind: Deliverable
metadata:
  name: polaris-demo
  namespace: rehan
  labels:
    app.kubernetes.io/component: deliverable
    app.tanzu.vmware.com/deliverable-type: web
    app.tanzu.vmware.com/delivery-commit-sha: main_70e7da6f849a75a945b2f4486e8ed08f80d4d337
spec:
  params:
  - name: gitops_ssh_secret
    value: gitops-ssh
  - name: gitops_sub_path
    value: config/rehan/polaris-demo
  source:
    git:
      url: https://github.com/Mpluya/config-polaris-demo.git
      ref:
        branch: main

