apiVersion: carto.run/v1alpha1
kind: Deliverable
metadata:
  name: polaris-demo
  namespace: rehan
  labels:
    app.kubernetes.io/component: deliverable
    app.tanzu.vmware.com/deliverable-type: web
spec:
  params:
  - name: gitops_ssh_secret
    value: gitops-ssh
  - name: gitops_sub_path
    value: config/rehan/polaris-demo
  source:
    git:
      url: https://github.com/Mpluya/config-deliverable-prod.git
      ref:
        branch: main

