apiVersion: carto.run/v1alpha1
kind: Deliverable
metadata:
  name: pony-pet
  namespace: mae
  labels:
    app.kubernetes.io/component: deliverable
    app.kubernetes.io/part-of: pony-pet
    app.tanzu.vmware.com/deliverable-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/language: java
    apps.tanzu.vmware.com/workload-type: web
    deliverable-intent: code-promotion
    kapp.k14s.io/app: "1662668565516243318"
    kapp.k14s.io/association: v1.1def198a99a7041f6450085119f5632d
    workload-intent: code-analysis
spec:
  params:
  - name: gitops_ssh_secret
    value: gitops-ssh
  - name: gitops_sub_path
    value: config/mae/pony-pet
  source:
    git:
      url: https://github.com/Mpluya/config-deliverable-prod.git
      ref:
        branch: main

